import { createSlice, PayloadAction } from '@reduxjs/toolkit'

import type { AppState } from '../../app/store'

export interface AnswersState {
    answersAmount: number,
    currentQuestion: number,
    testAnswers: string[],
    correctAnswers: boolean[],
}


const answersAmount = 15;

const initialState: AnswersState = {
    answersAmount,
    currentQuestion: 0,
    testAnswers: new Array(answersAmount).fill(""),
    correctAnswers: new Array(answersAmount).fill(false),
}

interface IAddAnswerType {
    answerNumber: number;
    answer: string;
}


export const answersSlice = createSlice({
    name: 'answers',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        answerQuestion: (state, action: PayloadAction<IAddAnswerType>) => {
            // Redux Toolkit allows us to write "mutating" logic in reducers. It
            // doesn't actually mutate the state because it uses the Immer library,
            // which detects changes to a "draft state" and produces a brand new
            // immutable state based off those changes
            state.testAnswers[action.payload.answerNumber] = action.payload.answer
        },
        incrementCurrentQuestion: (state) => {
            if (state.currentQuestion < state.answersAmount - 1) {
                state.currentQuestion += 1
            }
        },
        decrementCurrentQuestion: (state) => {
            if (state.currentQuestion > 0) {
                state.currentQuestion -= 1
            }
        },
        setCurrentQuestion: (state, action: PayloadAction<number>) => {
            state.currentQuestion = action.payload
        }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
})

export const { answerQuestion, decrementCurrentQuestion, incrementCurrentQuestion, setCurrentQuestion } = answersSlice.actions

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectAnswers = (state: AppState) => state.answers.testAnswers;

export const selectCurrentQuestion = (state: AppState) => state.answers.currentQuestion;

export default answersSlice.reducer