export const currentQuestionIndexName = 'currentQuestionIndex'
export const checkedAnswersName = 'checkedAnswers'
export const questionsInStorageName = 'questionsInStorageName'
export const questionsCategoryName = 'categoryName'
export const snippetsCategoryName = 'categoryName'
export const isGuestName = 'isGuestName'
